## Project
name: autodesk_account_matching
version: "1.0"
config-version: 2
profile: autodesk_account_matching

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  autodesk_account_matching:
    staging:
      +materialized: view
    marts:
      +materialized: table
