autodesk_account_matching:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: autodesk_account_matching_db
      schema: dev
      warehouse: autodesk_account_matching
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: autodesk_account_matching_db
      schema: prod
      warehouse: autodesk_account_matching