-- Determined by asking an LLM on all rows (original fuzzy matching ver.)
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES WHERE FINAL_LLM_DECISION = 'Yes';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES WHERE FINAL_LLM_DECISION = 'Maybe';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES WHERE FINAL_LLM_DECISION = 'No';

-- Determined by asking an LLM on all rows
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'Yes';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'Maybe';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'No';

-- Determined automatically via avg similarity above a threshold
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_BACKUP_THRESHOLD WHERE FINAL_LLM_DECISION = 'Yes';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_BACKUP_THRESHOLD WHERE FINAL_LLM_DECISION = 'Maybe';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_BACKUP_THRESHOLD WHERE FINAL_LLM_DECISION = 'No';

-- Determined by asking an LLM on only the top-1 most similar rows
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_THRESH_1 WHERE FINAL_LLM_DECISION = 'Yes';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_THRESH_1 WHERE FINAL_LLM_DECISION = 'Maybe';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.RAW.STEP10_FINAL_LLM_ROW_MATCHES_EMBED_THRESH_1 WHERE FINAL_LLM_DECISION = 'No';

-- Test set
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.TEST.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'Yes';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.TEST.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'Maybe';
SELECT * FROM AUTODESK_ACCOUNT_MATCHING_DB.TEST.STEP10_FINAL_LLM_ROW_MATCHES_EMBED WHERE FINAL_LLM_DECISION = 'No';
