DECLARE
    drop_stmt STRING;
    c CURSOR FOR
        SELECT 'DROP TABLE IF EXISTS ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME AS stmt
        FROM AUTODESK_ACCOUNT_MATCHING_DB.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'TEST' AND TABLE_TYPE = 'BASE TABLE';
BEGIN
    FOR rec IN c DO
        drop_stmt := rec.stmt;
        EXECUTE IMMEDIATE drop_stmt;
    END FOR;
    RETURN 'All tables dropped';
END;

CREATE OR REPLACE FILE FORMAT AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
PARSE_HEADER = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE TABLE AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_ORIGINAL
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES',
      FILE_FORMAT => 'AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff',
      FILES => ('master_test.csv')
    )
  )
);

COPY INTO AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_ORIGINAL
FROM @AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES
FILES = ('master_test.csv')
FILE_FORMAT = (
  FORMAT_NAME = AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

CREATE OR REPLACE TABLE AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_SAME_COLUMNS_20_MATCHES
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES',
      FILE_FORMAT => 'AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff',
      FILES => ('master_test_10_rows_identical_10_rows_similar_rest_different.csv')
    )
  )
);

COPY INTO AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_SAME_COLUMNS_20_MATCHES
FROM @AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES
FILES = ('master_test_10_rows_identical_10_rows_similar_rest_different.csv')
FILE_FORMAT = (
  FORMAT_NAME = AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

CREATE OR REPLACE TABLE AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_SIMILAR_COLUMNS_20_MATCHES
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES',
      FILE_FORMAT => 'AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff',
      FILES => ('master_test_semantically_identical_columns.csv')
    )
  )
);

COPY INTO AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_SIMILAR_COLUMNS_20_MATCHES
FROM @AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES
FILES = ('master_test_semantically_identical_columns.csv')
FILE_FORMAT = (
  FORMAT_NAME = AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

CREATE OR REPLACE TABLE AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_UNRELATED_COLUMNS_20_MATCHES
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES',
      FILE_FORMAT => 'AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff',
      FILES => ('master_test_unrelated_columns.csv')
    )
  )
);

COPY INTO AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_UNRELATED_COLUMNS_20_MATCHES
FROM @AUTODESK_ACCOUNT_MATCHING_DB.TEST.MASTER_FILES
FILES = ('master_test_unrelated_columns.csv')
FILE_FORMAT = (
  FORMAT_NAME = AUTODESK_ACCOUNT_MATCHING_DB.TEST.csv_header_ff
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;